-- Скрипт создания таблиц для Supabase (Talk Sensor)
-- Выполните этот SQL в редакторе SQL (SQL Editor) вашей панели Supabase.

-- 1. Таблица Shops (Магазины/Кофейни)
CREATE TABLE IF NOT EXISTS public.shops (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    yandex_folder text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Добавим тестовую кофейню (shop_id = 8, как в pipeline)
INSERT INTO public.shops (id, name, yandex_folder) 
VALUES (8, 'Ак мечеть', '/Kavabanga_Point_1/')
ON CONFLICT (id) DO UPDATE 
SET name = EXCLUDED.name, yandex_folder = EXCLUDED.yandex_folder;

-- 2. Таблица Dialogs (Диалоги и оценки)
CREATE TABLE IF NOT EXISTS public.dialogs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id bigint REFERENCES public.shops(id) ON DELETE CASCADE,
    dialog_index integer NOT NULL,
    original_audio_file text,
    clean_text text,
    speakers_involved text[] DEFAULT '{}'::text[],
    transcript jsonb DEFAULT '[]'::jsonb,
    score numeric(3,1), -- оценка от 0.0 до 5.0
    text_analysis text,
    audio_url text,
    lost_revenue_rub numeric DEFAULT 0,
    audit_details jsonb DEFAULT '{}'::jsonb,
    tags text[] DEFAULT '{}'::text[],
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Таблица App Status (Статус оркестратора)
CREATE TABLE IF NOT EXISTS public.app_status (
    id bigint PRIMARY KEY,
    is_analyzing boolean DEFAULT false,
    status_message text,
    last_run_at timestamp with time zone
);

-- Инициализируем одну запись статуса
INSERT INTO public.app_status (id, is_analyzing, status_message, last_run_at)
VALUES (1, false, 'Ready', now())
ON CONFLICT (id) DO NOTHING;

-- 4. Таблица Agent Telemetry (Состояние агентов для красивого офиса)
CREATE TABLE IF NOT EXISTS public.agent_telemetry (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_name text NOT NULL UNIQUE,
    status text DEFAULT 'IDLE', -- IDLE, BUSY
    active_task text DEFAULT '',
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Инициализируем агентов
INSERT INTO public.agent_telemetry (agent_name, status, active_task)
VALUES 
('Audio Diarization Agent', 'IDLE', ''),
('Diarization Editor', 'IDLE', ''),
('QA Analyst', 'IDLE', '')
ON CONFLICT (agent_name) DO NOTHING;

-- Разрешаем публичный доступ (RFE-политики) для удобства тестирования
ALTER TABLE public.shops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dialogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_telemetry ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous read shops" ON public.shops FOR SELECT USING (true);
CREATE POLICY "Allow anonymous read dialogs" ON public.dialogs FOR SELECT USING (true);
CREATE POLICY "Allow anonymous read app_status" ON public.app_status FOR SELECT USING (true);
CREATE POLICY "Allow anonymous read agent_telemetry" ON public.agent_telemetry FOR SELECT USING (true);

-- Разрешаем запись для service_role / anon (если без RLS для тестов)
CREATE POLICY "Allow all to write shops" ON public.shops FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all to write dialogs" ON public.dialogs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all to write app_status" ON public.app_status FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all to write agent_telemetry" ON public.agent_telemetry FOR ALL USING (true) WITH CHECK (true);
